"use client";
import { useRef, useState } from "react";
import { Button, Card, CardContent, CardHeader, CardTitle, Field, Input, Switch, useToast } from "@/components/ui";
import { useWorkspace } from "@/components/layout";

export function WorkspaceSettings() {
  const { apiKey, compact, organizationId, setApiKey, setCompact, setOrganizationId, setWorkspaceShopId, workspaceShopId } = useWorkspace(); const { toast } = useToast(); const [busy, setBusy] = useState(false); const requestKey = useRef(crypto.randomUUID()); const ready = Boolean(apiKey.trim() && organizationId.trim());
  async function save() { setBusy(true); try { const response = await fetch("/api/workspace-preference", { method: "PUT", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json", "Idempotency-Key": requestKey.current }, body: JSON.stringify({ organizationId: organizationId.trim(), shopId: workspaceShopId.trim() || null, isCompact: compact }) }); const body = await response.json() as Readonly<{ code?: string }>; if (!response.ok) throw new Error(body.code ?? "workspace.preference_failed"); requestKey.current = crypto.randomUUID(); toast({ title: "Préférence de poste enregistrée", variant: "success" }); } catch (failure) { toast({ title: "Enregistrement impossible", description: failure instanceof Error ? failure.message : "Erreur inattendue", variant: "error" }); } finally { setBusy(false); } }
  return <Card><CardHeader><CardTitle>Configuration du poste</CardTitle><p className="text-sm text-text-secondary">Ces identifiants restent nécessaires jusqu’à la disponibilité des projections Organisation, Utilisateur et Boutiques.</p></CardHeader><CardContent className="grid gap-5"><div className="grid gap-4 lg:grid-cols-2"><Field label="Organisation" name="organization-id" required>{({ controlId }) => <Input autoComplete="organization" id={controlId} onChange={(event) => setOrganizationId(event.target.value)} value={organizationId} />}</Field><Field label="Clé d’accès" name="api-key" required>{({ controlId }) => <Input autoComplete="current-password" id={controlId} onChange={(event) => setApiKey(event.target.value)} type="password" value={apiKey} />}</Field><Field description="Contexte opérationnel des ventes et opérations de stock." label="Boutique de travail" name="workspace-shop-id">{({ controlId, descriptionId }) => <Input aria-describedby={descriptionId} id={controlId} onChange={(event) => setWorkspaceShopId(event.target.value)} placeholder="Identifiant de boutique" value={workspaceShopId} />}</Field><label className="flex min-h-11 items-center gap-3 self-end text-sm font-medium" htmlFor="compact-mode"><Switch checked={compact} id="compact-mode" onCheckedChange={setCompact} />Affichage compact</label></div><div className="flex justify-end"><Button disabled={!ready} isLoading={busy} onClick={() => void save()} variant="secondary">Enregistrer ce poste</Button></div></CardContent></Card>;
}
