"use client";

import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui";
import type { WorkspaceOrganization } from "./workspace-context";
import { logoutAction } from "./actions";

type TopbarProps = Readonly<{ onMenuOpen: () => void; onOrganizationChange: (value: string) => void; onShopChange: (value: string) => void; organizationId: string; organizations: readonly WorkspaceOrganization[]; shopId: string; shops: readonly Readonly<{ id: string; name: string; code: string }>[]; userLabel: string }>;
const selectClass = "min-h-11 min-w-0 rounded-md border border-border bg-surface px-3 text-sm font-semibold text-text-primary outline-none focus:border-primary focus:ring-3 focus:ring-primary/15";

export function Topbar({ onMenuOpen, onOrganizationChange, onShopChange, organizationId, organizations, shopId, shops, userLabel }: TopbarProps) {
  return <header className="sticky top-0 z-40 flex h-16 items-center gap-2 border-b border-border bg-surface/95 px-4 backdrop-blur sm:px-6 lg:px-8"><button aria-label="Ouvrir le menu" className="grid size-11 shrink-0 place-items-center rounded-md border border-border bg-surface p-0 text-text-primary hover:bg-surface-subtle md:hidden" onClick={onMenuOpen} type="button"><svg aria-hidden="true" className="size-5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16" /></svg></button><div className="min-w-0 flex-1"><label className="sr-only" htmlFor="current-organization">Organisation actuelle</label><select className={`${selectClass} max-w-full`} id="current-organization" onChange={(event) => onOrganizationChange(event.target.value)} value={organizationId}>{organizations.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</select></div><div className="hidden sm:block"><label className="sr-only" htmlFor="current-shop">Boutique de travail</label><select className={`${selectClass} max-w-56`} disabled={shops.length === 0} id="current-shop" onChange={(event) => onShopChange(event.target.value)} value={shopId}>{shops.length === 0 ? <option value="">Aucune boutique</option> : shops.map((shop) => <option key={shop.id} value={shop.id}>{shop.name}</option>)}</select></div><DropdownMenu><DropdownMenuTrigger asChild><button className="flex min-h-11 min-w-0 items-center gap-2 rounded-md px-2 text-left hover:bg-surface-subtle" type="button"><span aria-hidden="true" className="grid size-9 shrink-0 place-items-center rounded-full bg-primary/10 font-semibold text-primary">{userLabel.charAt(0).toUpperCase() || "U"}</span><span className="hidden max-w-36 truncate text-sm font-medium lg:block">{userLabel}</span><span aria-hidden="true" className="text-text-secondary">⌄</span></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>{userLabel}</DropdownMenuLabel><DropdownMenuSeparator /><form action={logoutAction}><DropdownMenuItem asChild><button className="w-full" type="submit">Se déconnecter</button></DropdownMenuItem></form></DropdownMenuContent></DropdownMenu></header>;
}
