"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState, type Dispatch, type ReactNode, type SetStateAction } from "react";
import { useRouter } from "next/navigation";

export type WorkspaceOrganization = Readonly<{ id: string; name: string; currency: string; role: string; preference: Readonly<{ shopId: string | null; isCompact: boolean }> | null; shops: readonly Readonly<{ id: string; name: string; code: string }>[] }>;
export type WorkspaceAccount = Readonly<{ id: string; email: string; displayName: string }>;
export type WorkspaceSession = Readonly<{ account: WorkspaceAccount; organizations: readonly WorkspaceOrganization[] }>;
type WorkspaceContextValue = Readonly<{ account: WorkspaceAccount | null; compact: boolean; loading: boolean; organizationId: string; organizations: readonly WorkspaceOrganization[]; setCompact: Dispatch<SetStateAction<boolean>>; setOrganizationId: (organizationId: string) => void; setWorkspaceShopId: Dispatch<SetStateAction<string>>; workspaceShopId: string }>;
const WorkspaceContext = createContext<WorkspaceContextValue | null>(null);

export function WorkspaceProvider({ children, initialSession = null }: Readonly<{ children: ReactNode; initialSession?: WorkspaceSession | null }>) {
  const router = useRouter();
  const initialOrganization = initialSession?.organizations[0];
  const [organizationId, setOrganizationIdState] = useState(initialOrganization?.id ?? ""); const [workspaceShopId, setWorkspaceShopId] = useState(initialOrganization?.preference?.shopId ?? initialOrganization?.shops[0]?.id ?? ""); const [account, setAccount] = useState<WorkspaceAccount | null>(initialSession?.account ?? null); const [organizations, setOrganizations] = useState<readonly WorkspaceOrganization[]>(initialSession?.organizations ?? []); const [loading, setLoading] = useState(initialSession === null); const [compact, setCompact] = useState(initialOrganization?.preference?.isCompact ?? false);
  useEffect(() => { if (initialSession !== null) { if (initialSession.organizations.length === 0) { router.replace("/onboarding"); return; } const savedOrganization = window.localStorage.getItem("astu.workspace.organization"); const selected = initialSession.organizations.find(({ id }) => id === savedOrganization) ?? initialSession.organizations[0]; setOrganizationIdState(selected.id); setCompact(selected.preference?.isCompact ?? false); const preferredShop = selected.preference?.shopId ?? window.localStorage.getItem(`astu.workspace.shop.${selected.id}`); setWorkspaceShopId(selected.shops.find(({ id }) => id === preferredShop)?.id ?? selected.shops[0]?.id ?? ""); return; } let active = true; void fetch("/api/auth/me", { cache: "no-store" }).then(async (response) => { if (response.status === 401) { router.replace(`/login?next=${encodeURIComponent(`${window.location.pathname}${window.location.search}`)}`); return null; } if (!response.ok) throw new Error("auth.session_read_failed"); return response.json() as Promise<WorkspaceSession>; }).then((session) => { if (!active || session === null) return; setAccount(session.account); setOrganizations(session.organizations); if (session.organizations.length === 0) { router.replace("/onboarding"); return; } const savedOrganization = window.localStorage.getItem("astu.workspace.organization"); const selected = session.organizations.find(({ id }) => id === savedOrganization) ?? session.organizations[0]; setOrganizationIdState(selected.id); setCompact(selected.preference?.isCompact ?? false); const preferredShop = selected.preference?.shopId ?? window.localStorage.getItem(`astu.workspace.shop.${selected.id}`); setWorkspaceShopId(selected.shops.find(({ id }) => id === preferredShop)?.id ?? selected.shops[0]?.id ?? ""); }).catch(() => { if (active) router.replace("/login"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [initialSession, router]);
  useEffect(() => { if (organizationId) window.localStorage.setItem("astu.workspace.organization", organizationId); }, [organizationId]);
  useEffect(() => { if (organizationId && workspaceShopId) window.localStorage.setItem(`astu.workspace.shop.${organizationId}`, workspaceShopId); }, [organizationId, workspaceShopId]);
  const setOrganizationId = useCallback((value: string) => { const organization = organizations.find(({ id }) => id === value); setOrganizationIdState(value); if (organization) { const preferredShop = organization.preference?.shopId ?? window.localStorage.getItem(`astu.workspace.shop.${organization.id}`); setWorkspaceShopId(organization.shops.find(({ id }) => id === preferredShop)?.id ?? organization.shops[0]?.id ?? ""); setCompact(organization.preference?.isCompact ?? false); } }, [organizations]);
  const value = useMemo(() => ({ account, compact, loading, organizationId, organizations, setCompact, setOrganizationId, setWorkspaceShopId, workspaceShopId }), [account, compact, loading, organizationId, organizations, setOrganizationId, workspaceShopId]);
  return <WorkspaceContext.Provider value={value}>{children}</WorkspaceContext.Provider>;
}

export function useWorkspace(): WorkspaceContextValue { const context = useContext(WorkspaceContext); if (context === null) throw new Error("useWorkspace must be used within WorkspaceProvider."); return context; }
