"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useWorkspace } from "@/components/layout";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, EmptyState, ErrorState, Field, Input, Skeleton, useToast } from "@/components/ui";

type Shop = Readonly<{ id: string; name: string; code: string; isActive: boolean }>;

export function ShopsView() {
  const { organizationId } = useWorkspace(); const { toast } = useToast(); const [items, setItems] = useState<readonly Shop[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!organizationId) return; setLoading(true); setError(null); try { const response = await fetch(`/api/administration/shops?organizationId=${encodeURIComponent(organizationId)}`, { cache: "no-store" }); const body = await response.json() as { code?: string; items?: readonly Shop[] }; if (!response.ok) throw new Error(body.code); setItems(body.items ?? []); } catch (failure) { setError(failure instanceof Error ? failure.message : "Erreur inattendue"); } finally { setLoading(false); } }, [organizationId]);
  useEffect(() => { const reload = () => void load(); reload(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = event.currentTarget; const data = new FormData(form); try { const response = await fetch("/api/administration/shops", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ organizationId, name: data.get("name"), code: data.get("code") }) }); const body = await response.json() as { code?: string }; if (!response.ok) throw new Error(body.code); form.reset(); await load(); toast({ title: "Boutique créée", variant: "success" }); } catch (failure) { toast({ title: "Création impossible", description: failure instanceof Error ? failure.message : "Erreur inattendue", variant: "error" }); } finally { setBusy(false); } }
  return <div className="grid gap-6"><Card><CardHeader><CardTitle>Nouvelle boutique</CardTitle><p className="text-sm text-text-secondary">Ajoutez un point de vente à l’organisation actuelle.</p></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-[1fr_12rem_auto]" onSubmit={(event) => void create(event)}><Field label="Nom" name="shop-name" required>{({ controlId }) => <Input id={controlId} name="name" placeholder="Tié-Tié" required />}</Field><Field description="Court et stable." label="Code" name="shop-code" required>{({ controlId, descriptionId }) => <Input aria-describedby={descriptionId} id={controlId} name="code" placeholder="TIE-TIE" required />}</Field><Button className="self-end" disabled={!organizationId} isLoading={busy} type="submit">Créer la boutique</Button></form></CardContent></Card>{loading ? <div className="grid gap-3"><Skeleton className="h-16" /><Skeleton className="h-16" /></div> : null}{!loading && error ? <ErrorState description={error} onRetry={() => void load()} /> : null}{!loading && !error && items.length === 0 ? <EmptyState description="Aucune boutique n’existe encore dans cette organisation." title="Aucune boutique" /> : null}{!loading && !error && items.length > 0 ? <Card><CardHeader><CardTitle>Boutiques</CardTitle></CardHeader><CardContent><div className="grid gap-3">{items.map((shop) => <div className="flex min-h-16 items-center justify-between gap-4 rounded-md border border-border px-4 py-3" key={shop.id}><div><p className="font-medium">{shop.name}</p><p className="text-sm text-text-secondary">{shop.code}</p></div><Badge variant={shop.isActive ? "success" : "neutral"}>{shop.isActive ? "Active" : "Inactive"}</Badge></div>)}</div></CardContent></Card> : null}</div>;
}
